### PR TITLE
Blog App - Feature/authentication

### PR DESCRIPTION
**Pull request by oliverSCZ**
In this PR I have added authentication and implemented the following functions

- Removed current_user method in ApplicationController, devise will provide us with one.
- Register a new user
- User can login with a combination of email and password.
- Store hashed passwords to the database.
- Ask for confirmation of email.
- Password resets
- Please refer to the [README](https://github.com/oliverSCZ/blog-app#readme) file on how to test for emails

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @oliverSCZ, @danalvrz, @rtonata88 , 

You have done a fantastic job so far in this project. Keep up! :rocket: 
There are some issues that you still need to work on to go to the next project but you are almost there!

Screenshot from 2022-04-12 20-44-47




# To Highlights

- [x] Git/GitHub workflow has been followed :heavy_check_mark: 
- [x] Linters are correctly set up :heavy_check_mark: 
- [x] Pull Request has a title and summary :heavy_check_mark: 


## Required Changes ♻️

- [ ] Hi Team, from the requirements of this project, the views in the devise for the registration and login need to be modified to match [these wireframes](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) and their styling.

_Check the comments under the review._

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oliverSCZ** [comment]
Hello @FrederickMih sorry but I don't understand you, can you please say what part exactly... by the way we don't have wireframes for the registration...

**Comment by FrederickMih** [comment]
Hi @oliverSCZ, What I meant is that you should make sure that your sign-up page and the sign-in page should look like that provided in your project requirements.  So you need to modify these pages so that they should match the ones provided in the original design guidelines.

Hope this can help :pray:

**Review by GzimAsani — APPROVED** [review]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
